---

- name: "Teamcity | Get distribution"
  get_url:
    url: "http://download.jetbrains.com/teamcity/TeamCity-{{ teamcity_version }}.tar.gz"
    dest: "/tmp/TeamCity-{{ teamcity_version }}.tar.gz"
    validate_certs: no
  tags:
    - teamcity

- name: "Teamcity | Unpack distribution"
  become: yes
  become_user: root
  unarchive:
    src: "/tmp/TeamCity-{{ teamcity_version }}.tar.gz"
    dest: "/opt/teamcity"
    copy: "no"
  tags:
    - teamcity