---

- name: "Teamcity | Detect installation"
  stat:
    path: "/opt/teamcity/TeamCity/webapps/ROOT/WEB-INF/buildServerConfigurator.xml"
  register: config_file

- name: "Teamcity | Get version"
  shell: 'curl localhost:8111 | grep TeamCity | grep build | cut -d " " -f10'
  register: teamcity_installed_version