---

- name: "TeamCity | Service | Stop"
  become: yes
  become_user: root
  shell: '"{{ teamcity_install_dir }}/TeamCity/bin/teamcity-server.sh" stop'

- name: "TeamCity | Service | Start"
  become: yes
  become_user: root
  shell: '"{{ teamcity_install_dir }}/TeamCity/bin/teamcity-server.sh" start'
  register: teamcity_status
  failed_when: '"Tomcat started." not in "{{ teamcity_status.stdout }}"'